version: '3.8'

services:
  # App
  app:
    image: ${DOCKER_HUB_URL}/${NAME}:${ENV}
    container_name: ${NAME}-${ENV}-app
    command: [ "scripts/entrypoint.sh" ]
    ports:
      - "8002:${BASE_PORT}"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - net

networks:
  net:
    name: ${NAME}-${ENV}-net